### ISSUE TITLE
Basic.t does not include accountId on requests

### ISSUE THREAD

**Issue by mdecimus** [fastmail/JMAP-TestSuite#37]
Hi,

I have started testing our JMAP server with **JMAP-TestSuite** and I noticed that it does not include the `accountId` field on requests, for example this is the first request sent by `basic.t`:

```
{
  "using": [
    "urn:ietf:params:jmap:core",
    "urn:ietf:params:jmap:mail"
  ],
  "methodCalls": [
    [
      "Email/get",
      {
        "ids": [
          "i00"
        ]
      },
      "e"
    ]
  ]
}
```

And this is the adapter configuration I am using:

```
{
  "adapter": "Cyrus",
  "base_uri": "http://localhost:8080",
  "credentials": [
    {
      "accountId": "i01",
      "username": "i01",
      "password": "mypassword"
    }
  ],
  "virtual_domain_enabled": 0
}
```

Our server has full RFC8620 + RFC8621 support and I would like to test it using Basic Auth for the time being. Which adapter do you recommend I use? Also if you could provide any documentation or guidelines on how to use the test suite it would be really appreciated. 

Thank you in advance.

**Comment by mdecimus** [comment]
Hi @brong and @rjbs ,

Just wondering if there are plans to update JMAP-TestSuite? I found some issues such that it is not including the `accountId` on requests and sending non-conformant requests (or better said, conforming to a previous draft of JMAP Mail) such as this one:

```
{
  "methodCalls": [
    [
      "Email/import",
      {
        "emails": {
          "msg": {
            "blobId": "b5ca1f501800a62179544e8af9a49963ecde9f8f77c7dafae418592791218d847dd01",
            "isAnswered": false,
            "isDraft": false,
            "isFlagged": false,
            "isUnread": false,
            "mailboxIds": {
              "i00": true
            }
          }
        }
      },
      "d"
    ]
  ],
  "using": [
    "urn:ietf:params:jmap:core",
    "urn:ietf:params:jmap:mail"
  ]
}

```

Thank you!

**Comment by rjbs** [comment]
@mdecimus Hi!  Sorry it took so long to reply!

Yes, we would like to keep this up to date.  We run the test suite against our JMAP implementation on every branch, which allows some very old forms, so we haven't always caught things that are no longer permitted.  We can have a look at what we can *obviously* find, but if you send us notes on specific errors, we'll make updates.  (I see you have a big commit of your work, and we'd be happy to merge targeted commits!)

I'll try to be in touch more in the future so we can make this test suite useful for more folks.  Also, Cyrus has quite a lot of JMAP test code in its own test suite, and I'd like us to move more of those bits out into the JMAP-TestSuite, for tests about compliance rather than weird bugs we've had.

**Comment by rjbs** [comment]
@mdecimus Hey, it's me again.

We spun up a VM and built Stalwart and ran through the test suite.  Great!  (We got hung up for a bit because Ubuntu's packaged cargo was choking on --release, maybe rust-lang#94914?  It was taking 10m to build with no end in sight, using 6GB of ram…)  Anyway, we got the tests running and hit just the error you provided.  We'll fix it that error.

We'll give the test suite a look over, but as you can imagine, it's going to be hard for us to notice things that are no long compliant just by looking. I'd love to spend some time giving it a thorough read-through, but I don't want to make any promises.  Meantime, like I said, we will gladly address problems you point out here!

Getting Stalwart up and going was *mostly* painless, but we hit a couple snags:

We installed stalwart-cli and couldn't get it running against the default config:
```
Enter admin credentials or press [ENTER] to use OAuth: [we typed admin]
Failed to connect to JMAP server https://127.0.0.1:8080: Transport error: error sending request for url (https://127.0.0.1:8080/.well-known/jmap): error trying to connect: presented server name type wasn't supported.
```

We couldn't create a test user (jdoe@example.com) because of that, so we used admin.  This was okay, but the admin user seemed to have no role:inbox mailbox (not too surprising) so some tests failed.  This was the main thing.  Also, we weren't keen to bother making a Let's Encrypt cert, and had to patch the Stalwart test suite adapter to disable SSL checks.

We were surprised that we get a urn:ietf:params:jmap:error:notRequest when passing invalid arguments.  That is, the error you cited above is that we're passing in things like `isFlagged: false`, which is an unknown parameter to the method.  That should return a method-level `invalidArguments` rather than aborting the whole call.  The method call itself, despite bad arguments, does match Invocation.  Maybe you already knew this, but I thought I'd mention it.

Anyway, we remain excited to help shape up bits of the test suite, so don't hesitate to let us know what you find.

**Comment by mdecimus** [comment]
Hi @rjbs ,

> I'll try to be in touch more in the future so we can make this test suite useful for more folks. Also, Cyrus has quite a lot of JMAP test code in its own test suite, and I'd like us to move more of those bits out into the JMAP-TestSuite, for tests about compliance rather than weird bugs we've had.

No problem, I ended up [forking JMAP-TestSuite](https://github.com/stalwartlabs/jmap-test-suite) and added support for Stalwart JMAP there. I never coded in Perl before so my changes are hardcoded (and/or hackish) and the tests that require pristine accounts have to be done manually. 

> We'll give the test suite a look over, but as you can imagine, it's going to be hard for us to notice things that are no long compliant just by looking. I'd love to spend some time giving it a thorough read-through, but I don't want to make any promises. Meantime, like I said, we will gladly address problems you point out here!

I was able to pass all JMAP-TestSuite tests except a few minor details, mostly related to the type of error messages returned. I also found a minor issue on the ``Changes`` test, when the results are paginated the test suite expects the older changes first while the JMAP spec recommends the newer changes to be returned first. But overall everything went well.

I also wrote [multiple tests](https://github.com/stalwartlabs/jmap-server/tree/main/src/tests) in Rust to test the different JMAP functions and I am currently using Stalwart with TMail-Web and Ltt.rs (the only two JMAP clients that are functional at the moment) without any compatibility issues (although TMail does not fully support EmailSubmissions yet). So for the time being everything looks well and I no longer need help with this issue.

> We got hung up for a bit because Ubuntu's packaged cargo was choking on --release, maybe rust-lang#94914? It was taking 10m to build with no end in sight, using 6GB of ram

Yes, Rust is notoriously slow when compiling large projects. I would say that a build time over 10m is normal which I admit is quite frustrating. On my laptop it takes around 13 minutes and on the Github actions workers sometimes around 20 minutes.

> Failed to connect to JMAP server https://127.0.0.1:8080: Transport error: error sending request for url (https://127.0.0.1:8080/.well-known/jmap): error trying to connect: presented server name type wasn't supported.

That error message is most likely because Rust TLS does not support certificates issued to IP addresses. You should use ``https://localhost:8080`` instead as the JMAP base URL.

> This was okay, but the admin user seemed to have no role:inbox mailbox (not too surprising) so some tests failed. 

That is correct, the admin user is not meant to be used as a JMAP account so the default folders are not created (but you can manually create them if you like). New accounts created with ``stalwart-cli`` do have all default mailboxes.

> We were surprised that we get a urn:ietf:params:jmap:error:notRequest when passing invalid arguments. 

Thanks, I am aware of that and I briefly mentioned it above. It is related to the deserialization step that converts JSON to objects, in some cases when it is not possible to deserialize the request due to unexpected input a generic error is returned instead. It is a low priority issue but I do plan to fix it at some point.

> Anyway, we remain excited to help shape up bits of the test suite, so don't hesitate to let us know what you find.

Thank you very much for the help!
